#!/bin/bash

wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add
sudo dpkg -i google-chrome-stable_current_amd64.deb
