#!/bin/bash

sudo snap install remmina
sudo snap connect remmina:avahi-observe :avahi-observe
sudo snap connect remmina:cups-control :cups-control
sudo snap connect remmina:mount-observe :mount-observe
sudo snap connect remmina:password-manager-service :password-manager-service

cp group_rdp_raspberry_192-168-1-60.remmina ~/snap/remmina/4047/.local/share/remmina/
