#!/bin/bash

rm -f ~/Programs/footboard2PC/networkIP
rm -f ~/Programs/footboard2PC/serviceIP

if [ "$1" == -i ]; then 
    initialize=yes
    shift
    version=$1
elif [ "$1" == -a ]; then
    all=yes
    shift
    version=$1
elif [ "$1" == -s ]; then
    service=yes
    shift
    version="no-version"
elif [ "$1" == -n ]; then
    network=yes
    shift
    version="no-version"
fi

if  [ -z ${version} ]; then
    echo "Version parameter must be assigned"
    echo "USAGE: 
        rasp-setup [-a] [-s] [-n] [-i] version"
    exit 1
elif ! [ -z ${initialize} ]; then
   wget "https://github.com/ZepHakase22/ecubit/releases/download/v$version/initialize-footboard2hf"
   chmod +x ./initialize-footboard2hf
   ./initialize-footboard2hf $version
elif ! [ -z ${all} ]; then
    chmod +x ./initialize-footboard2hf
    ./initialize-footboard2hf $version
    source ~/.bashrc
    create-service
    source ~/.bashrc
    create-network
    exit 0
elif ! [ -z ${service} ]; then
    source ~/.bashrc
    create-service
elif ! [ -z ${network} ]; then
    source ~/.bashrc
    create-network
else
    chmod +x ./initialize-footboard2hf
    ./initialize-footboard2hf $version
    source ~/.bashrc
    create-service
    source ~/.bashrc
    create-network
fi
exit 0
